import { Prompt, PromptCategory, PromptType } from './types';

export const INITIAL_PROMPTS: Prompt[] = [
  // --- WEBAPP PROMPTS ---
  {
    id: '1',
    title: 'Code Refactoring Expert',
    description: 'Analyze code for performance, readability, and security improvements.',
    content: "You are a Senior Software Engineer. Review the following code snippet. Identify any potential bugs, performance bottlenecks, or security vulnerabilities. Suggest specific refactoring steps to improve readability and maintainability, adhering to clean code principles. \n\nCode snippet:\n[PASTE CODE HERE]",
    tags: ['coding', 'refactoring', 'clean-code'],
    category: PromptCategory.CODING,
    type: PromptType.WEBAPP,
    author: 'DevMaster',
    imageUrl: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: '5',
    title: 'React Component Generator',
    description: 'Generate functional React components with Tailwind CSS.',
    content: "Create a reusable React functional component for a [COMPONENT NAME]. Use TypeScript and Tailwind CSS for styling. Ensure it is responsive and accessible. The component should accept the following props: [PROPS LIST].",
    tags: ['coding', 'react', 'frontend'],
    category: PromptCategory.CODING,
    type: PromptType.WEBAPP,
    author: 'FrontendWiz',
    imageUrl: 'https://images.unsplash.com/photo-1633356122544-f134324a6cee?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'w1',
    title: 'Next.js API Route Handler',
    description: 'Create a robust Next.js App Router API handler with error handling.',
    content: "Write a Next.js App Router API route handler (GET/POST) for [RESOURCE]. Include input validation using Zod, error handling, and appropriate HTTP status codes. Assume interaction with a database via Prisma.",
    tags: ['nextjs', 'backend', 'api'],
    category: PromptCategory.CODING,
    type: PromptType.WEBAPP,
    author: 'FullStackDev',
    imageUrl: 'https://images.unsplash.com/photo-1618477247222-ac5913054c90?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'w2',
    title: 'E-commerce Dashboard UI',
    description: 'Design a data-rich dashboard structure for an e-commerce admin panel.',
    content: "Plan the component structure for an E-commerce Admin Dashboard. It should include a Sidebar, Header, Stats Cards (Revenue, Orders), and a Recent Orders Table. Suggest React state management strategy (Context vs Redux) and how to handle data fetching for these widgets.",
    tags: ['dashboard', 'ui-design', 'structure'],
    category: PromptCategory.CODING,
    type: PromptType.WEBAPP,
    author: 'UIDesignPro',
    imageUrl: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'w3',
    title: 'Tailwind Landing Page Hero',
    description: 'Generate the HTML/Classes for a high-conversion landing page hero section.',
    content: "Write the HTML and Tailwind CSS classes for a modern SaaS landing page hero section. It needs a large H1, a subheadline, a 'Get Started' primary button, a 'Learn More' secondary button, and a placeholder for a hero image on the right side. Ensure mobile responsiveness.",
    tags: ['tailwind', 'landing-page', 'css'],
    category: PromptCategory.MARKETING,
    type: PromptType.WEBAPP,
    author: 'GrowthHacker',
    imageUrl: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'w4',
    title: 'Authentication Context Provider',
    description: 'Boilerplate for a secure React Auth Context using Firebase or Custom JWT.',
    content: "Create a React Context provider for Authentication. It should handle login, logout, and checking the current user status. Include a custom hook `useAuth` to access the context easily. Handle loading states while checking auth status.",
    tags: ['react', 'auth', 'security'],
    category: PromptCategory.CODING,
    type: PromptType.WEBAPP,
    author: 'SecurityFirst',
    imageUrl: 'https://images.unsplash.com/photo-1614064641938-3bcee52942c7?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'w5',
    title: 'Responsive Grid Gallery',
    description: 'CSS Grid layout for a masonry-style image gallery.',
    content: "Write the CSS (or Tailwind classes) for a responsive masonry image gallery. It should have 1 column on mobile, 2 on tablets, and 3 or 4 on desktops. Images should have a rounded border and a subtle hover zoom effect.",
    tags: ['css', 'layout', 'gallery'],
    category: PromptCategory.CREATIVE,
    type: PromptType.WEBAPP,
    author: 'CSSWizard',
    imageUrl: 'https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?auto=format&fit=crop&w=800&q=80',
  },

  // --- SYSTEM PROMPTS ---
  {
    id: '2',
    title: 'Blog Post Generator',
    description: 'Create engaging, SEO-friendly blog posts on any topic.',
    content: "Write a comprehensive, engaging, and SEO-optimized blog post about [TOPIC]. The tone should be [TONE, e.g., professional, witty]. Include a catchy title, an introduction that hooks the reader, well-structured body paragraphs with subheadings, and a concluding summary. Target audience: [AUDIENCE].",
    tags: ['writing', 'content-creation', 'seo'],
    category: PromptCategory.WRITING,
    type: PromptType.SYSTEM,
    author: 'ContentPro',
    imageUrl: 'https://images.unsplash.com/photo-1499750310159-52f0f83ad497?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: '4',
    title: 'Complex Concept Simplifier',
    description: 'Explain difficult concepts simply (ELI5).',
    content: "Explain the concept of [CONCEPT] to me as if I were 5 years old. Use simple analogies, avoid jargon, and focus on the core idea.",
    tags: ['learning', 'productivity', 'explanation'],
    category: PromptCategory.PRODUCTIVITY,
    type: PromptType.SYSTEM,
    author: 'TeacherAI',
    imageUrl: 'https://images.unsplash.com/photo-1509228468518-180dd4864904?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 's1',
    title: 'Empathetic Customer Support',
    description: 'Act as a supportive customer service agent handling complaints.',
    content: "You are a senior customer support agent known for your empathy and problem-solving skills. A customer is complaining about [ISSUE]. Write a response that acknowledges their frustration, apologizes sincerely, explains the cause (if known), and offers a concrete solution or compensation.",
    tags: ['business', 'support', 'writing'],
    category: PromptCategory.MARKETING,
    type: PromptType.SYSTEM,
    author: 'SupportHero',
    imageUrl: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 's2',
    title: 'Data Analyst Assistant',
    description: 'Interpret data trends and suggest business actions.',
    content: "You are an expert Data Analyst. I will provide a dataset summary or a list of trends. You need to interpret what these trends mean for the business and suggest 3 actionable steps we can take to capitalize on them. \n\nData: [INSERT DATA]",
    tags: ['data', 'analytics', 'business'],
    category: PromptCategory.PRODUCTIVITY,
    type: PromptType.SYSTEM,
    author: 'DataMind',
    imageUrl: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 's3',
    title: 'Mock Interviewer',
    description: 'Conduct a job interview for a specific role.',
    content: "Act as a hiring manager for a [JOB TITLE] position at a [COMPANY TYPE]. Ask me an interview question. Wait for my response. Then grade my response and ask the next question. Do this for 5 questions total.",
    tags: ['career', 'interview', 'roleplay'],
    category: PromptCategory.PRODUCTIVITY,
    type: PromptType.SYSTEM,
    author: 'HRBot',
    imageUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 's4',
    title: 'Socratic Tutor',
    description: 'Learn through guided questioning rather than direct answers.',
    content: "Act as a Socratic Tutor. When I ask a question about [TOPIC], do not give me the answer directly. Instead, ask me a guiding question that helps me derive the answer myself. Continue this back-and-forth until I understand the concept.",
    tags: ['learning', 'education', 'philosophy'],
    category: PromptCategory.PRODUCTIVITY,
    type: PromptType.SYSTEM,
    author: 'PhilosophyAI',
    imageUrl: 'https://images.unsplash.com/photo-1524178232363-1fb2b075b655?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 's5',
    title: 'Travel Itinerary Planner',
    description: 'Plan a detailed trip based on location and interests.',
    content: "Create a 3-day travel itinerary for [CITY]. I am interested in [INTERESTS e.g., food, history, nature]. Include morning, afternoon, and evening activities, along with recommended restaurants.",
    tags: ['travel', 'planning', 'lifestyle'],
    category: PromptCategory.CREATIVE,
    type: PromptType.SYSTEM,
    author: 'Wanderlust',
    imageUrl: 'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?auto=format&fit=crop&w=800&q=80',
  },

  // --- IMAGE PROMPTS ---
  {
    id: 'i1',
    title: 'Cyberpunk Cityscape',
    description: 'Detailed prompt for generating futuristic neon cities.',
    content: "A futuristic cyberpunk city street at night, raining, neon lights reflecting on wet pavement, towering skyscrapers with holographic advertisements, flying cars in the sky, cinematic lighting, photorealistic 8k, highly detailed, octane render, blade runner style.",
    tags: ['midjourney', 'dalle', 'scifi'],
    category: PromptCategory.CINEMATIC,
    type: PromptType.IMAGE,
    author: 'VisualArtist',
    imageUrl: 'https://images.unsplash.com/photo-1535868463750-c78d9543614f?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'i2',
    title: 'Minimalist Logo Design',
    description: 'Generate clean, modern vector-style logos.',
    content: "A minimalist vector logo design for a tech startup named 'Nexus', geometric shapes, negative space, clean lines, black and white, flat design, vector illustration, adobe illustrator style, professional corporate identity.",
    tags: ['design', 'logo', 'vector'],
    category: PromptCategory.ABSTRACT,
    type: PromptType.IMAGE,
    author: 'DesignBot',
    imageUrl: 'https://images.unsplash.com/photo-1626785774573-4b799314346d?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'i3',
    title: 'Portrait of a Warrior',
    description: 'High-fantasy character portrait generation.',
    content: "Close-up portrait of an elven warrior with intricate silver armor, glowing blue eyes, white hair, forest background, soft natural lighting, bokeh effect, artstation style, digital painting by Greg Rutkowski, fantasy art.",
    tags: ['fantasy', 'character', 'portrait'],
    category: PromptCategory.CREATIVE,
    type: PromptType.IMAGE,
    author: 'FantasyFan',
    imageUrl: 'https://images.unsplash.com/photo-1519074069444-1ba4fff66d16?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'i4',
    title: 'Isometric 3D Room',
    description: 'Cute isometric 3D render of a cozy gaming room.',
    content: "Isometric view of a cozy gamer bedroom, low poly style, pastel colors, soft lighting, 3d render, blender, pc setup with rgb, potted plants, bean bag, cozy atmosphere, high resolution.",
    tags: ['3d', 'isometric', 'cozy'],
    category: PromptCategory.CREATIVE,
    type: PromptType.IMAGE,
    author: 'PolyArtist',
    imageUrl: 'https://images.unsplash.com/photo-1555680202-c86f0e12f086?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'i5',
    title: 'Oil Painting Landscape',
    description: 'Classic impressionist style oil painting prompt.',
    content: "Oil painting of a vast sunflower field at sunset, van gogh style, thick brush strokes, vibrant yellow and orange colors, distant farmhouse, emotional, textured, traditional art style.",
    tags: ['art', 'painting', 'classic'],
    category: PromptCategory.CREATIVE,
    type: PromptType.IMAGE,
    author: 'ArtHistorian',
    imageUrl: 'https://images.unsplash.com/photo-1543857770-7245f1c63601?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'i6',
    title: 'Watercolor Cat',
    description: 'Soft and artistic watercolor style animal portrait.',
    content: "A fluffy maine coon cat sitting on a window sill, watercolor painting style, soft edges, pastel colors, ink splashes, dreamy atmosphere, artistic, white background.",
    tags: ['art', 'watercolor', 'animal'],
    category: PromptCategory.CREATIVE,
    type: PromptType.IMAGE,
    author: 'PaintBrush',
    imageUrl: 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'i7',
    title: 'Abstract Geometric Shapes',
    description: 'Modern 3D abstract background wallpaper.',
    content: "Abstract 3D composition of floating geometric shapes, spheres and cubes, matte black and gold materials, dramatic studio lighting, minimalist, high contrast, 4k wallpaper.",
    tags: ['abstract', '3d', 'background'],
    category: PromptCategory.ABSTRACT,
    type: PromptType.IMAGE,
    author: 'GeoForm',
    imageUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=800&q=80',
  },

  // --- VIDEO PROMPTS ---
  {
    id: 'v1',
    title: 'Drone Shot of Coastline',
    description: 'Prompt for generating realistic aerial footage.',
    content: "Cinematic drone shot flying over a rocky coastline with crashing waves, golden hour lighting, 4k resolution, high dynamic range, smooth motion, national geographic style nature documentary footage.",
    tags: ['sora', 'runway', 'nature'],
    category: PromptCategory.REALISTIC,
    type: PromptType.VIDEO,
    author: 'CineMaster',
    imageUrl: 'https://images.unsplash.com/photo-1476610182048-b716b8518aae?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'v2',
    title: 'Cyberpunk Car Chase',
    description: 'Action-packed sci-fi video generation prompt.',
    content: "Fast-paced car chase through a neon-lit cyberpunk city tunnel, sparks flying, motion blur, intense speed, cinematic camera angles, dynamic lighting, 60fps, action movie style.",
    tags: ['action', 'scifi', 'vehicle'],
    category: PromptCategory.CINEMATIC,
    type: PromptType.VIDEO,
    author: 'ActionDir',
    imageUrl: 'https://images.unsplash.com/photo-1599395028026-6d63435b89a8?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'v3',
    title: 'Macro Flower Blooming',
    description: 'Time-lapse style video generation of nature.',
    content: "Time-lapse close up of a pink lotus flower blooming, morning dew drops on petals, soft sunlight changing position, high detail, 8k resolution, slow smooth transformation.",
    tags: ['nature', 'timelapse', 'macro'],
    category: PromptCategory.REALISTIC,
    type: PromptType.VIDEO,
    author: 'NatureLover',
    imageUrl: 'https://images.unsplash.com/photo-1592652426563-7e7931f7c327?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'v4',
    title: 'Orbital Space View',
    description: 'Epic view of Earth from space station.',
    content: "View from a space station window looking down at Earth, slow rotation, sunrise over the curvature of the planet, lens flare, stars in background, photorealistic 8k, gravity movie style.",
    tags: ['space', 'scifi', 'epic'],
    category: PromptCategory.CINEMATIC,
    type: PromptType.VIDEO,
    author: 'SpaceExplorer',
    imageUrl: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'v5',
    title: 'Underwater Coral Reef',
    description: 'Peaceful underwater marine life exploration.',
    content: "Underwater shot of a colorful coral reef, schools of tropical fish swimming, sunlight rays piercing through the water surface, clear blue water, 4k, peaceful atmosphere.",
    tags: ['nature', 'underwater', 'calm'],
    category: PromptCategory.REALISTIC,
    type: PromptType.VIDEO,
    author: 'OceanLife',
    imageUrl: 'https://images.unsplash.com/photo-1546026423-cc4642628d2b?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'v6',
    title: 'Slow Motion Rain',
    description: 'Cinematic slow motion rain falling on pavement.',
    content: "Extreme slow motion close-up of rain droplets hitting a puddle on dark asphalt, rippling water rings, reflection of city lights, cinematic moody atmosphere, high frame rate.",
    tags: ['rain', 'slow-motion', 'moody'],
    category: PromptCategory.CINEMATIC,
    type: PromptType.VIDEO,
    author: 'MoodSetter',
    imageUrl: 'https://images.unsplash.com/photo-1515694346937-94d85e41e6f0?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'v7',
    title: 'FPV Drone Forest',
    description: 'Fast first-person view drone flying through trees.',
    content: "FPV drone footage flying fast and low through a dense pine forest, dodging tree trunks, dynamic banking turns, motion blur, immersive speed, daylight, 4k resolution.",
    tags: ['drone', 'fpv', 'nature'],
    category: PromptCategory.REALISTIC,
    type: PromptType.VIDEO,
    author: 'PilotCam',
    imageUrl: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&w=800&q=80',
  },
];